<?php

namespace NB\UsersBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSeatseller(){

        $queryBuilder = $this
            ->createQueryBuilder('u')
            //    ->leftJoin('t.frequency', 'frequency')
            ->where('u.roles like :role')
            ->setParameters(array('role' => '%ROLE_SEATSELLER%' ))
        ;
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();
        // On récupère les résultats à partir de la Query
        $results = $query->getResult();
        //  dump($results); exit;

        return $results;


    }
}
